"""Add Assignment model

Revision ID: 18c79270e0d5
Revises: 8ebe4cf02c89
Create Date: 2026-07-14 17:23:45.425827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18c79270e0d5'
down_revision: Union[str, None] = '8ebe4cf02c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action_id', sa.String(), nullable=True),
    sa.Column('volunteer_id', sa.String(), nullable=False),
    sa.Column('incident_id', sa.String(), nullable=True),
    sa.Column('location_node_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['response_actions.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['location_node_id'], ['stadium_nodes.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignments')
    # ### end Alembic commands ###
