"""add_is_accessible_to_edges

Revision ID: 8ebe4cf02c89
Revises: 5a892b123456
Create Date: 2026-07-13 17:38:32.145530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ebe4cf02c89'
down_revision: Union[str, None] = '5a892b123456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('response_actions', sa.Column('simulation_id', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('simulation_version', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('simulation_timestamp', sa.DateTime(), nullable=True))
    op.add_column('response_actions', sa.Column('node_id', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('operational_summary', sa.String(), nullable=True))
    op.add_column('response_actions', sa.Column('metrics', sa.JSON(), nullable=True))
    op.add_column('response_actions', sa.Column('evidence', sa.JSON(), nullable=True))
    op.add_column('response_actions', sa.Column('improvement_estimate', sa.JSON(), nullable=True))
    op.add_column('response_actions', sa.Column('alternatives', sa.JSON(), nullable=True))
    op.add_column('response_actions', sa.Column('timeline', sa.JSON(), nullable=True))
    op.add_column('response_actions', sa.Column('execution_status', sa.String(), nullable=False))
    op.add_column('response_actions', sa.Column('execution_result', sa.JSON(), nullable=True))
    op.add_column('response_actions', sa.Column('correlation_id', sa.String(), nullable=True))
    op.alter_column('response_actions', 'incident_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key(None, 'response_actions', 'stadium_nodes', ['node_id'], ['id'])
    op.add_column('stadium_edges', sa.Column('is_accessible', sa.Boolean(), nullable=False))
    op.add_column('telemetry_events', sa.Column('event_type', sa.String(), nullable=False))
    op.add_column('telemetry_events', sa.Column('payload', sa.JSON(), nullable=False))
    op.alter_column('telemetry_events', 'node_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('telemetry_events', 'value')
    op.drop_column('telemetry_events', 'metric')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telemetry_events', sa.Column('metric', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('telemetry_events', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('telemetry_events', 'node_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('telemetry_events', 'payload')
    op.drop_column('telemetry_events', 'event_type')
    op.drop_column('stadium_edges', 'is_accessible')
    op.drop_constraint(None, 'response_actions', type_='foreignkey')
    op.alter_column('response_actions', 'incident_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('response_actions', 'correlation_id')
    op.drop_column('response_actions', 'execution_result')
    op.drop_column('response_actions', 'execution_status')
    op.drop_column('response_actions', 'timeline')
    op.drop_column('response_actions', 'alternatives')
    op.drop_column('response_actions', 'improvement_estimate')
    op.drop_column('response_actions', 'evidence')
    op.drop_column('response_actions', 'metrics')
    op.drop_column('response_actions', 'operational_summary')
    op.drop_column('response_actions', 'node_id')
    op.drop_column('response_actions', 'simulation_timestamp')
    op.drop_column('response_actions', 'simulation_version')
    op.drop_column('response_actions', 'simulation_id')
    # ### end Alembic commands ###
