"""add is_accessible

Revision ID: 987acc97ff70
Revises: 7dc7d7318a05
Create Date: 2026-07-08 15:29:28.660660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987acc97ff70'
down_revision: Union[str, None] = '7dc7d7318a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stadium_nodes', sa.Column('is_accessible', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stadium_nodes', 'is_accessible')
    # ### end Alembic commands ###
